# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='proflepic',
            field=models.CharField(default='', max_length=255),
        ),
    ]
