# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-10 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instapix', '0004_auto_20190309_1607'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentModel',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='LikeModel',
            new_name='Like',
        ),
        migrations.RenameModel(
            old_name='PostModel',
            new_name='Post',
        ),
    ]
