# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-12 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapix', '0005_auto_20190310_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['location'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank='', default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank='', default='', max_length=255),
        ),
    ]
